version: '3.8'

services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: ecsdb
      POSTGRES_USER: ecsuser
      POSTGRES_PASSWORD: ecspassword
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ecsuser -d ecsdb"]
      interval: 30s
      timeout: 10s
      retries: 3

  backend:
    build: ./backend
    ports:
      - "4000:4000"
    environment:
      - POSTGRES_HOST=postgres
      - POSTGRES_DB=ecsdb
      - POSTGRES_USER=ecsuser
      - POSTGRES_PASSWORD=ecspassword
      - POSTGRES_PORT=5432
      - NODE_ENV=development
    depends_on:
      postgres:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:4000/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  frontend:
    build: 
      context: ./frontend
      dockerfile: Dockerfile.local
    ports:
      - "3000:80"
    environment:
      - REACT_APP_API_URL=http://localhost:4000
    depends_on:
      backend:
        condition: service_healthy

volumes:
  postgres_data: