version: '3.8'

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: ecsdb
      POSTGRES_USER: ecsuser
      POSTGRES_PASSWORD: ecspassword
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - todo-network

  backend:
    build: .
    environment:
      POSTGRES_HOST: db
      POSTGRES_DB: ecsdb
      POSTGRES_USER: ecsuser
      POSTGRES_PASSWORD: ecspassword
      PORT: 4000
    ports:
      - "4000:4000"
    depends_on:
      - db
    networks:
      - todo-network

  frontend:
    build: ../frontend
    environment:
      REACT_APP_API_URL: http://localhost:4000
    ports:
      - "3000:80"
    depends_on:
      - backend
    networks:
      - todo-network

volumes:
  postgres_data:

networks:
  todo-network:
    driver: bridge